// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcjfzsdmmvwflpgsexwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjamZ6c2RtbXZ3ZmxwZ3NleHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTEzOTcsImV4cCI6MjA2Mjg4NzM5N30.9GLXbW5mnqopqmt6-jp60EVj_FAoEENwJEtLndSlzJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);